import type { CommandSpecBuilder } from './types'
import { AUTH_LOGIN_USER_ACTION_HINT } from '../../errors'

export function addAuthCommandSpecs ({ add, dryRunOption, example, formatOption, group, yesOption }: CommandSpecBuilder): void {
  group('auth', 'Manage saved OAuth credentials explicitly.', ['Only auth login opens a browser; every other command fails with exit 3 when credentials are missing or rejected and tells the agent to ask the developer to sign in.', 'Credentials persist in auth.json under an absolute $XDG_CONFIG_HOME/poki, an absolute %LOCALAPPDATA%\\Poki on Windows, or ~/.config/poki, with restricted file permissions. Empty and relative environment paths are ignored.', AUTH_LOGIN_USER_ACTION_HINT])
  add({ path: ['auth', 'login'], summary: 'Developer-only browser sign-in that saves OAuth credentials.', options: [formatOption], agent_execution: { allowed: false, required_actor: 'developer', reason: 'The saved credentials must belong to the developer environment and would be lost with an LLM or agent sandbox.', developer_commands: { global: 'poki auth login', project_dependency: 'npx poki auth login' } }, behavior: [AUTH_LOGIN_USER_ACTION_HINT, 'When the developer runs it, the command opens the browser, waits for the local OAuth callback, and saves credentials. Progress is written to stderr; the final token-free status document goes to stdout.', 'Accepted current limitation: the CLI uses a temporary OS-assigned callback port with no CLI-generated nonce, secret callback path, or callback timeout. It waits until the callback arrives or the process is interrupted.'], side_effects: ['When run by the developer, opens a browser, starts a temporary local HTTP callback, and replaces the saved auth file in the developer environment.'], examples: [example('poki auth login', 'Developer runs this manually; an agent must only relay the global or project-dependency command from agent_execution.developer_commands.')], network: { method: 'MULTIPLE', path: ['https://app.poki.dev/signin', 'temporary local HTTP callback on an OS-assigned port', 'https://auth.poki.io/auth/exchange'], contacts_api: true }, risk: 'mutation', retry_safe: false })
  add({ path: ['auth', 'status'], summary: 'Inspect stored credentials without printing tokens or contacting an API.', options: [formatOption], behavior: ['Offline credential-file check: reports presence, JWT expiry when readable, and refreshability. Never prints access or refresh tokens.'], network: { method: 'none', path: 'local auth file', contacts_api: false }, risk: 'offline' })
  add({ path: ['auth', 'logout'], summary: 'Delete saved OAuth credentials.', options: [dryRunOption, yesOption, formatOption], behavior: ['Removes only the saved OAuth credential file; POKI_UPLOAD_TOKEN and POKI_ACCESS_TOKEN environment variables are never read or modified here.'], side_effects: ['Deletes the saved auth file.'], network: { method: 'none', path: 'local auth file', contacts_api: false }, risk: 'destructive', destructive: true })
}
