import { listCapabilities } from '../../list-capabilities'
import type { CommandSpecBuilder } from './types'

export function addGameEventCommandSpecs ({ apiAction, argument, dataOption, example, gameOption, group, listOptionsFor, mutationOptions, option }: CommandSpecBuilder): void {
  group('game-events', 'List and manage custom SDK event definitions.')
  apiAction(['game-events', 'list'], 'List game event definitions.', { method: 'GET', path: '/games/:gameID/game_events', contacts_api: true }, ['can_read_owned_game_events'], { options: [gameOption, ...listOptionsFor(listCapabilities.gameEvents)], behavior: ['This endpoint supports sorting and pagination. It does not support generic filters.'] })
  const gameEventValueOptions = [option('--category', 'string', "SDK category; 1-64 characters, no '/' or '^'."), option('--action', 'string', "SDK what; legacy API field; 1-64 characters, no '/' or '^'."), option('--label', 'string', "SDK action; legacy API field; at most 64 characters, no '/' or '^'."), option('--description', 'string', 'Human-readable purpose; required on create.')]
  const gameEventCreateValueOptions = gameEventValueOptions.map(value => ['--category', '--action', '--description'].includes(value.name) ? { ...value, required: 'unless --data' } : value)
  const gameEventStateOptions = [option('--enabled', 'boolean', 'Whether analytics exposes the event.'), option('--include-in-funnel', 'boolean', 'Whether funnels may select the event.')]
  apiAction(['game-events', 'create'], 'Create an event definition that the server enables and includes in funnels.', { method: 'POST', path: '/games/:gameID/game_events', contacts_api: true }, ['can_edit_owned_game_events'], { options: [gameOption, ...gameEventCreateValueOptions, dataOption, ...mutationOptions], behavior: ['Duplicate normalized event keys conflict on the server.'], missing_input: '--category, --action, and --description, or --data', examples: [example('poki game-events create --category progress --action level_complete --description "Completed a level" --dry-run', 'Preview a correctly mapped SDK event definition.')] })
  apiAction(['game-events', 'update'], 'Update an event definition, including enabled and funnel state.', { method: 'PATCH', path: '/games/:gameID/game_events/:eventID', contacts_api: true }, ['can_edit_owned_game_events'], { arguments: [argument('event-id', 'Event definition ID.')], options: [gameOption, ...gameEventValueOptions, ...gameEventStateOptions, dataOption, ...mutationOptions], behavior: ['Changing the normalized event key can conflict with another definition on the server.'], missing_input: 'an event ID and changed fields', examples: [example('poki game-events update EVENT_ID --no-enabled --dry-run', 'Preview disabling an event definition.')] })
}
