import { listCapabilities } from '../../list-capabilities'
import type { CommandSpecBuilder } from './types'

export function addGameChangeRequestCommandSpecs ({ apiAction, argument, collectionGetBehavior, dataOption, example, gameOption, group, listOptionsFor, mutationOptions, option, outputOptions }: CommandSpecBuilder): void {
  group('game-change-requests', 'List, inspect, create, and cancel developer game changes.')
  apiAction(['game-change-requests', 'list'], 'List requests for a game.', { method: 'GET', path: '/games/:gameID/change_requests', contacts_api: true }, ['can_read_owned_game_change_requests'], { options: [gameOption, ...listOptionsFor(listCapabilities.gameChangeRequests)] })
  apiAction(['game-change-requests', 'get'], 'Get one request by filtering the game collection.', { method: 'GET', path: '/games/:gameID/change_requests?filter[id]', contacts_api: true }, ['can_read_owned_game_change_requests'], { arguments: [argument('request-id', 'Request ID.')], options: [gameOption, ...outputOptions], behavior: [collectionGetBehavior], missing_input: 'a request ID' })
  apiAction(['game-change-requests', 'create'], 'Request a title, thumbnail, or custom CSP change.', { method: 'POST', path: '/games/:gameID/change_requests', contacts_api: true }, ['can_create_owned_game_change_requests'], { options: [gameOption, option('--title', 'string', 'Requested title; 3-128 characters.'), option('--thumbnail-file', 'path', 'Image encoded as base64.'), option('--custom-content-security-policy', 'string', 'Requested CSP; an empty string removes the custom CSP.'), option('--csp-reason', 'source=reason', 'CSP justification up to 200 characters; repeatable.', { repeatable: true }), dataOption, ...mutationOptions], behavior: ['The backend validates profanity, image content, privacy-policy prerequisites, and CSP reasons.', 'Dry-run previews describe thumbnail encoding and size but omit the base64 value.'], side_effects: ['May create a pending request or apply eligible changes immediately.'], missing_input: 'at least one requested change or --data', examples: [example('poki game-change-requests create --title "New title" --dry-run', 'Preview a game-title change request.')] })
  apiAction(['game-change-requests', 'cancel'], 'Cancel a pending request created by the authenticated user; no named permission is checked.', { method: 'PATCH', path: '/games/:gameID/change_requests/:requestID', contacts_api: true }, [], { arguments: [argument('request-id', 'Request ID.')], options: [gameOption, ...mutationOptions], risk: 'destructive', destructive: true, missing_input: 'a request ID' })
}
