import { listCapabilities } from '../../list-capabilities'
import type { CommandSpecBuilder } from './types'

export function addGameEventFunnelCommandSpecs ({ apiAction, argument, dataOption, example, gameOption, group, listOptionsFor, mutationOptions, option, outputOptions, requestMutationOptions }: CommandSpecBuilder): void {
  group('game-event-funnels', 'List and manage ordered custom-event funnels.')
  apiAction(['game-event-funnels', 'list'], 'List funnels.', { method: 'GET', path: '/games/:gameID/game_event_funnels', contacts_api: true }, ['can_read_owned_game_events'], { options: [gameOption, ...listOptionsFor(listCapabilities.gameEventFunnels)], behavior: ['This endpoint supports sorting and pagination. It does not support generic filters.'] })
  apiAction(['game-event-funnels', 'get'], 'Get one funnel.', { method: 'GET', path: '/games/:gameID/game_event_funnels/:funnelID', contacts_api: true }, ['can_read_owned_game_events'], { arguments: [argument('funnel-id', 'Funnel ID.')], options: [gameOption, ...outputOptions], missing_input: 'a funnel ID' })
  for (const actionName of ['create', 'update'] as const) {
    apiAction(['game-event-funnels', actionName], `${actionName === 'create' ? 'Create' : 'Update'} a funnel with ordered events.`, { method: actionName === 'create' ? 'POST' : 'PATCH', path: actionName === 'create' ? '/games/:gameID/game_event_funnels' : '/games/:gameID/game_event_funnels/:funnelID', contacts_api: true }, ['can_edit_owned_game_events'], { arguments: actionName === 'update' ? [argument('funnel-id', 'Funnel ID.')] : undefined, options: [gameOption, option('--title', 'string', 'Funnel title; 1-128 characters.', { required: actionName === 'create' ? 'unless --data' : undefined }), option('--event', 'string', "Ordered frontend Category^What^Action key from dbt_p4d_game_events_funnel_v2.event, sourced from backend category^action^label; '^' is the separator; repeatable 1-50 times.", { required: actionName === 'create' ? 'unless --data' : undefined, repeatable: true }), dataOption, ...mutationOptions], behavior: actionName === 'create' ? ["events preserves the CLI argument order. Use dbt_p4d_game_events_funnel_v2.event verbatim; it is encoded in frontend order as Category^What^Action from backend fields category^action^label, including an empty final Action after the second '^'."] : ["--event replaces the complete ordered event list. Use the analytics event value verbatim rather than rebuilding or parsing the '^'-delimited key."], missing_input: actionName === 'update' ? 'a funnel ID and changed fields' : '--title and at least one --event, or --data', examples: actionName === 'create' ? [example('poki game-event-funnels create --title "Tutorial" --event "progress^tutorial^start" --event "progress^tutorial^complete" --dry-run', 'Preview an ordered funnel using canonical frontend Category^What^Action analytics keys.')] : [example('poki game-event-funnels update FUNNEL_ID --event "progress^tutorial^start" --dry-run', 'Preview replacing a funnel event order.')] })
  }
  apiAction(['game-event-funnels', 'delete'], 'Delete a funnel.', { method: 'DELETE', path: '/games/:gameID/game_event_funnels/:funnelID', contacts_api: true }, ['can_edit_owned_game_events'], { arguments: [argument('funnel-id', 'Funnel ID.')], options: [gameOption, ...requestMutationOptions], behavior: ['Soft deletion on the server with no CLI restore operation.'], risk: 'destructive', destructive: true, missing_input: 'a funnel ID' })
}
