import { listCapabilities } from '../../list-capabilities'
import type { CommandSpecBuilder } from './types'

export function addPlayerFeedbackQuestionCommandSpecs ({ apiAction, argument, dataOption, example, gameOption, group, listOptionsFor, mutationOptions, option, outputOptions, requestMutationOptions, waitOptions }: CommandSpecBuilder): void {
  group('player-feedback-questions', 'List, inspect, create, and delete generated feedback questions.', ['Generation is asynchronous; status progresses through pending, processing, and then completed or failed. Poll player-feedback-questions get until a terminal status.'])
  apiAction(['player-feedback-questions', 'list'], 'List questions for a game.', { method: 'GET', path: '/games/:gameID/player_feedback_questions', contacts_api: true }, ['can_read_owned_player_feedback'], { options: [gameOption, ...listOptionsFor(listCapabilities.playerFeedbackQuestions)], behavior: ['This endpoint supports sorting and pagination. It does not support generic filters.'] })
  apiAction(['player-feedback-questions', 'get'], 'Get one question and generated response.', { method: 'GET', path: '/games/:gameID/player_feedback_questions/:questionID', contacts_api: true }, ['can_read_owned_player_feedback'], { arguments: [argument('question-id', 'Question ID.')], options: [gameOption, ...outputOptions, ...waitOptions('Poll until status reaches completed or failed.')], behavior: ['--wait polls until status is completed or failed and adds meta.wait {final_state, polls, waited_ms}.'], missing_input: 'a question ID' })
  apiAction(['player-feedback-questions', 'create'], 'Queue feedback analysis over explicit dates and message types.', { method: 'MULTIPLE', path: ['POST /games/:gameID/player_feedback_questions', 'GET /games/:gameID/player_feedback_questions/:createdQuestionID (--wait only)'], contacts_api: true }, ['can_create_owned_player_feedback_question', 'can_read_owned_player_feedback'], { options: [gameOption, option('--question', 'string', 'Required natural-language question unless supplied by --data.', { required: 'unless --data' }), option('--start-date', 'date', 'Required UTC YYYY-MM-DD date; converted to Unix seconds.', { required: 'unless --data' }), option('--end-date', 'date', 'Required UTC YYYY-MM-DD date; converted to Unix seconds and must not precede start-date.', { required: 'unless --data' }), option('--message-type', 'enum', 'At least one of thumbs_up, thumbs_down, or bugreport; repeatable.', { required: 'unless --data', repeatable: true, values: ['thumbs_up', 'thumbs_down', 'bugreport'] }), dataOption, ...mutationOptions, ...waitOptions('After creation, poll until generation status reaches completed or failed.')], permission_logic: 'can_create_owned_player_feedback_question is required for creation; --wait additionally requires can_read_owned_player_feedback for every question polling GET.', behavior: ['--wait polls the created question until status is completed or failed and adds meta.wait.', 'If polling fails after creation, PLAYER_FEEDBACK_QUESTION_CREATE_WAIT_FAILED is non-retryable and carries the created question, the cause, and an executable details.recovery.resume_poll action; do not create the question again.', 'If a successful create response has no usable ID, the same action-level error preserves any normalized created resource and provides details.recovery.inspect_created_question; list current questions and do not create again.'], missing_input: '--question, dates, and message types, or --data', examples: [example('poki player-feedback-questions create --question "What blocks progression?" --start-date 2026-07-01 --end-date 2026-07-31 --message-type bugreport --dry-run', 'Preview a bounded feedback-analysis request.')] })
  apiAction(['player-feedback-questions', 'delete'], 'Delete a generated question.', { method: 'DELETE', path: '/games/:gameID/player_feedback_questions/:questionID', contacts_api: true }, ['can_delete_owned_player_feedback_question'], { arguments: [argument('question-id', 'Question ID.')], options: [gameOption, ...requestMutationOptions], risk: 'destructive', destructive: true, missing_input: 'a question ID' })
}
