import { listCapabilities } from '../../list-capabilities'
import type { CommandSpecBuilder } from './types'

export function addPlayerFitTestCommandSpecs ({ apiAction, argument, collectionGetBehavior, dataOption, example, gameOption, group, listOptionsFor, mutationOptions, option, outputOptions, testingAudienceDiscovery }: CommandSpecBuilder): void {
  group('player-fit-tests', 'List, inspect, create, and stop Player Fit tests.')
  apiAction(['player-fit-tests', 'list'], 'List tests for a game.', { method: 'GET', path: '/games/:gameID/player_fit_tests', contacts_api: true }, ['can_read_owned_player_fit_tests'], { options: [gameOption, ...listOptionsFor(listCapabilities.playerFitTests)], behavior: ['This endpoint supports filters but returns its complete matching collection in one response; sorting and pagination options do not exist.'] })
  apiAction(['player-fit-tests', 'get'], 'Get one test by filtering the game collection.', { method: 'GET', path: '/games/:gameID/player_fit_tests?filter[id]', contacts_api: true }, ['can_read_owned_player_fit_tests'], { arguments: [argument('test-id', 'Test ID.')], options: [gameOption, ...outputOptions], behavior: [collectionGetBehavior], missing_input: 'a test ID' })
  apiAction(['player-fit-tests', 'create'], 'Create a test fixed at 500 target gameplays.', { method: 'POST', path: '/games/:gameID/player_fit_tests', contacts_api: true }, ['can_edit_owned_player_fit_tests'], { options: [gameOption, option('--version', 'string', 'Version to test.', { required: true }), option('--device-category', 'enum', 'Device audience.', { default: 'any', values: ['any', 'desktop', 'mobile'] }), option('--orientation', 'enum', 'Required screen orientation.', { default: 'both', values: ['both', 'portrait', 'landscape'] }), option('--category', 'integer', `Numeric category ID; repeatable up to five times. ${testingAudienceDiscovery}`, { repeatable: true }), option('--category-only', 'boolean', 'Restrict recruitment to the selected categories.', { default: false }), option('--country', 'string', 'Uppercase two-letter country code; repeatable.', { repeatable: true }), dataOption, ...mutationOptions], behavior: ['target_gameplays is fixed at 500 and cannot be overridden.', '--data accepts only audience fields; --version stays a flag.'], missing_input: '--version', examples: [example('poki player-fit-tests create --version VERSION_ID --device-category mobile --category 10 --dry-run', 'Preview a mobile-only test for one player category.')] })
  apiAction(['player-fit-tests', 'stop'], 'Stop an active test.', { method: 'POST', path: '/games/:gameID/player_fit_tests/:testID/@stop', contacts_api: true }, ['can_edit_owned_player_fit_tests'], { arguments: [argument('test-id', 'Test ID.')], options: [gameOption, ...mutationOptions], risk: 'destructive', destructive: true, missing_input: 'a test ID' })
}
