import { listCapabilities } from '../../list-capabilities'
import type { CommandSpecBuilder } from './types'

export function addPlayerFitTestCommandSpecs ({ apiAction, argument, collectionGetBehavior, dataOption, example, gameOption, group, listOptionsFor, mutationOptions, option, outputOptions, testingAudienceDiscovery }: CommandSpecBuilder): void {
  group('player-fit-tests', 'List, inspect, create, and stop Player Fit tests.')
  apiAction(['player-fit-tests', 'list'], 'List tests for a game.', { method: 'GET', path: '/games/:gameID/player_fit_tests', contacts_api: true }, ['can_read_owned_player_fit_tests'], { options: [gameOption, ...listOptionsFor(listCapabilities.playerFitTests)], behavior: ['This endpoint supports filters but returns its complete matching collection in one response; sorting and pagination options do not exist.', 'Filter by test_version=1 or test_version=2 to compare the same methodology. Results always describe the whole test; gameplay.device_category filtering is not supported.'] })
  apiAction(['player-fit-tests', 'get'], 'Get one test by filtering the game collection.', { method: 'GET', path: '/games/:gameID/player_fit_tests?filter[id]', contacts_api: true }, ['can_read_owned_player_fit_tests'], { arguments: [argument('test-id', 'Test ID.')], options: [gameOption, ...outputOptions], behavior: [collectionGetBehavior], missing_input: 'a test ID' })
  apiAction(['player-fit-tests', 'create'], 'Create a test fixed at 500 gameplays (v1) or pageviews (v2).', { method: 'POST', path: '/games/:gameID/player_fit_tests', contacts_api: true }, ['can_edit_owned_player_fit_tests'], { options: [gameOption, option('--version', 'string', 'Version to test.', { required: true }), option('--test-version', 'integer', 'Player Fit methodology: 1 for legacy, 2 for pageviews with per-device quotas (default: 2).', { values: ['1', '2'] }), option('--device-category', 'enum', 'Device audience; omission selects mobile, desktop, and tablet.', { values: ['mobile', 'desktop', 'tablet'], repeatable: true }), option('--orientation', 'enum', 'Required screen orientation.', { default: 'both', values: ['both', 'portrait', 'landscape'] }), option('--category', 'integer', `Numeric category ID; repeatable up to five times. ${testingAudienceDiscovery}`, { repeatable: true }), option('--category-only', 'boolean', 'Restrict recruitment to the selected categories.', { default: false }), option('--country', 'string', 'Uppercase two-letter country code; repeatable.', { repeatable: true }), dataOption, ...mutationOptions], behavior: ['target_count is fixed at 500 and cannot be overridden.', '--data accepts audience fields and test_version; --version stays the game build flag. V1 supports all devices, desktop, or mobile and tablet together. V2 supports every nonempty device combination.'], missing_input: '--version', examples: [example('poki player-fit-tests create --version VERSION_ID --test-version 1 --dry-run', 'Preview a legacy v1 test.'), example('poki player-fit-tests create --version VERSION_ID --device-category tablet --category 10 --dry-run', 'Preview a Tablet-only test for one player category.'), example('poki player-fit-tests create --version VERSION_ID --device-category mobile --device-category tablet --dry-run', 'Preview a test for touch devices.')] })
  apiAction(['player-fit-tests', 'stop'], 'Stop an active test.', { method: 'POST', path: '/games/:gameID/player_fit_tests/:testID/@stop', contacts_api: true }, ['can_edit_owned_player_fit_tests'], { arguments: [argument('test-id', 'Test ID.')], options: [gameOption, ...mutationOptions], risk: 'destructive', destructive: true, missing_input: 'a test ID' })
}
