import { listCapabilities } from '../../list-capabilities'
import type { CommandSpecBuilder } from './types'

export function addReviewCommandSpecs ({ apiAction, argument, dataOption, example, gameOption, group, listOptionsFor, mutationOptions, option, outputOptions }: CommandSpecBuilder): void {
  group('reviews', 'List, inspect, request, update, and close version reviews.')
  apiAction(['reviews', 'list'], 'List game or version reviews.', { method: 'GET', path: ['/games/:gameID/reviews', '/games/:gameID/versions/:versionID/reviews'], contacts_api: true }, ['can_read_owned_reviews'], { options: [gameOption, option('--version', 'string', 'Optional version filter.'), ...listOptionsFor(listCapabilities.reviews)] })
  apiAction(['reviews', 'get'], 'Get one review.', { method: 'GET', path: '/games/:gameID/versions/:versionID/reviews/:reviewID', contacts_api: true }, ['can_read_owned_reviews'], { arguments: [argument('version-id', 'Version ID.'), argument('review-id', 'Review ID.')], options: [gameOption, ...outputOptions], missing_input: 'a version ID and review ID' })
  apiAction(['reviews', 'request'], 'Queue QA for a processed version.', { method: 'POST', path: '/games/:gameID/versions/:versionID/reviews', contacts_api: true }, ['can_create_owned_reviews'], { options: [gameOption, option('--version', 'string', 'Processed version ID.', { required: true }), option('--developer-notes', 'string', 'Required unless supplied by --data.', { required: 'unless --data' }), dataOption, ...mutationOptions], behavior: ['The server requires the version to be in done state; poll poki versions get until state is done before requesting.', 'Approval and rejection are handled by the Poki review workflow; poll poki reviews list for the outcome.'], side_effects: ['Queues QA, notifies watchers, and may generate changelog notes.'], missing_input: '--version and developer notes' })
  apiAction(['reviews', 'update'], 'Update developer notes or seen state.', { method: 'PATCH', path: '/games/:gameID/versions/:versionID/reviews/:reviewID', contacts_api: true }, ['can_edit_owned_reviews'], { arguments: [argument('version-id', 'Version ID.'), argument('review-id', 'Review ID.')], options: [gameOption, option('--developer-notes', 'string', 'Replacement developer notes.'), option('--seen', 'boolean', 'Whether the developer has seen the review.'), dataOption, ...mutationOptions], missing_input: 'a version ID, review ID, and changed fields', examples: [example('poki reviews update VERSION_ID REVIEW_ID --seen --dry-run', 'Preview acknowledging a review response.')] })
  apiAction(['reviews', 'close'], 'Close a pending review.', { method: 'PATCH', path: '/games/:gameID/versions/:versionID/reviews/:reviewID', contacts_api: true }, ['can_edit_owned_reviews'], { arguments: [argument('version-id', 'Version ID.'), argument('review-id', 'Review ID.')], options: [gameOption, ...mutationOptions], behavior: ['Sends status=closed; only pending reviews can change status, and there is no reopen operation.'], risk: 'destructive', destructive: true, missing_input: 'a version ID and review ID' })
}
