export interface AudienceDefinition {
  id: number
  name: string
  enabled_for_testing: boolean
}

// Bundled snapshot of the content categories used by Poki for Developers.
// Keeping this data in the CLI makes category discovery deterministic and
// offline. The backend remains authoritative when a category is submitted.
const audienceEntries: Array<[number, string, boolean?]> = [
  [1, 'Racing Games', true],
  [2, 'Sports Games', true],
  [3, 'Action Games', true],
  [4, 'Games for Girls', true],
  [6, 'Adventure Games', true],
  [7, 'Brain Games', true],
  [8, 'Board Games', true],
  [9, 'Skill Games', true],
  [11, 'Battleship Games'],
  [12, 'Pool Games'],
  [13, 'Block Games', true],
  [14, 'Boxing Games'],
  [16, 'Hidden Object Games', true],
  [18, 'Cooking Games', true],
  [20, 'Decoration Games'],
  [23, 'Chess Games', true],
  [25, 'Music Games'],
  [27, 'Soccer Games', true],
  [29, 'Dress Up Games', true],
  [32, 'Boat Games'],
  [33, 'Checkers Games'],
  [34, 'Drawing Games', true],
  [35, 'Math Games', true],
  [37, 'Mouse Games', true],
  [38, 'Maze Games', true],
  [41, 'Mahjong Games'],
  [44, 'Make Up Games', true],
  [48, 'Platform Games', true],
  [49, 'Ragdoll Games', true],
  [50, 'Hair Games', true],
  [51, 'Motorbike Games'],
  [52, 'Shopping Games'],
  [53, 'Snake Games', true],
  [54, 'Sudoku Games'],
  [58, 'Zombie Games', true],
  [61, 'RPG Games'],
  [64, 'Animal Games', true],
  [65, 'War Games', true],
  [66, 'Strategy Games', true],
  [67, 'Point and Click Games', true],
  [68, 'Love Games'],
  [69, 'Management Games', true],
  [72, 'Puzzle Games', true],
  [74, 'Mini Games'],
  [76, 'Multiplayer Games', true],
  [77, 'Shooting Games', true],
  [78, 'Car Games', true],
  [80, 'Fighting Games', true],
  [81, 'Police Games', true],
  [82, 'Bicycle Games'],
  [83, 'Geography Games'],
  [84, 'Card Games', true],
  [85, 'Fashion Games', true],
  [86, 'Train Games'],
  [87, 'Construction Games'],
  [88, 'Christmas Games', true],
  [91, 'Simulation Games', true],
  [93, '3D Games', true],
  [95, 'Word Games'],
  [96, 'Funny Games', true],
  [99, 'Robot Games', true],
  [100, 'Doctor Games'],
  [102, 'Bubble Games'],
  [103, 'Arcade Games'],
  [118, 'Farm Games'],
  [129, 'Baseball Games'],
  [130, 'Basketball Games', true],
  [136, 'BMX Games'],
  [139, 'Bowling Games'],
  [144, 'Hunting Games'],
  [145, 'Cat Games', true],
  [157, 'Cricket Games'],
  [179, 'Golf Games'],
  [183, 'Halloween Games', true],
  [188, 'Hospital Games'],
  [201, 'Makeover Games', true],
  [209, 'Easter Games'],
  [211, 'Parking Games'],
  [222, 'Jigsaw Puzzle Games'],
  [228, 'Escape Games', true],
  [239, 'Skateboarding Games'],
  [242, 'Sniper Games', true],
  [249, 'Tank Games', true],
  [250, 'Typing Games', true],
  [251, 'Tennis Games'],
  [253, 'Archery Games'],
  [254, 'Bubble Shooter Games'],
  [257, 'Tower Defense Games', true],
  [260, 'Bike Games', true],
  [272, 'Mini Golf Games'],
  [274, 'Fishing Games'],
  [277, 'Pizza Games'],
  [279, 'Cake Games'],
  [281, 'Princess Games'],
  [333, 'Ninja Games', true],
  [377, 'Truck Games', true],
  [379, 'Airplane Games', true],
  [380, 'Tractor Games'],
  [381, 'Dog Games'],
  [383, 'Wrestling Games'],
  [384, 'Dragon Games'],
  [385, 'Gun Games', true],
  [386, 'Bus Games'],
  [388, 'Restaurant Games', true],
  [389, 'Dinosaur Games', true],
  [390, 'Monster Truck Games', true],
  [392, 'Solitaire Games', true],
  [399, 'GTA Games', true],
  [400, 'Logic Games', true],
  [404, 'Fish Games'],
  [414, 'Monkey Games'],
  [734, 'Flappy Bird Games'],
  [735, 'World Cup Games'],
  [738, 'Dirt Bike Games'],
  [744, 'Minecraft Games', true],
  [748, 'Surgery Games'],
  [750, '2 Player Games', true],
  [775, 'Ball Games', true],
  [792, 'Ice Cream Games'],
  [802, 'Penalty Games'],
  [823, 'Educational Games', true],
  [826, 'Scary Games', true],
  [832, 'Intelligence Games', true],
  [839, 'Food Games', true],
  [842, 'Monster Games', true],
  [843, 'Quiz Games'],
  [852, 'Classic Games', true],
  [854, 'Football Games'],
  [869, 'Unity Games'],
  [873, 'Papa\'s Games'],
  [885, 'Parkour Games', true],
  [893, 'Driving Games', true],
  [898, 'Hockey Games'],
  [903, 'Running Games', true],
  [905, 'Anime Games'],
  [909, 'Matching Games', true],
  [927, 'Stickman Games', true],
  [929, 'Games for Boys', true],
  [931, 'Superhero Games'],
  [933, 'Number Games'],
  [972, 'Magic Games'],
  [1013, 'Physics Games', true],
  [1014, 'Idle Games', true],
  [1018, 'Survival Games', true],
  [1082, 'Match 3 Games'],
  [1083, 'Army Games'],
  [1103, 'HTML5 Games'],
  [1120, '.io Games', true],
  [1122, 'Crafting Games', true],
  [1123, 'Olympics Games'],
  [1126, 'Cool Games', true],
  [1130, 'Clicker Games', true],
  [1131, 'Slime Games'],
  [1136, 'Battle Royale Games'],
  [1137, 'App Store Games'],
  [1139, 'Crazy Games', true],
  [1140, 'Popular Games'],
  [1141, 'New Games'],
  [1143, 'Online Games'],
  [1147, 'Video Games'],
  [1149, 'Meme Games'],
  [1154, 'Flash Games'],
  [1155, 'Merge Games', true],
  [1161, 'Henry Stickmin Games'],
  [1162, 'Horror Games'],
  [1164, 'First Person Shooter Games', true],
  [1165, 'Color Games', true],
  [1166, 'Story Games'],
  [1167, 'Horse Games'],
  [1168, 'Co-op Games', true],
  [1169, 'Space Games'],
  [1171, 'Retro Games', true],
  [1177, 'Winter Games', true],
  [1178, 'Drifting Games', true],
  [1180, 'Nitrome Games'],
  [1185, 'Obby Games', true],
  [1186, 'Watermelon Games', true],
  [1187, 'Cozy Games', true],
  [1189, 'All Categories'],
  [1190, 'Mobile Games'],
  [1193, 'Difficult Games'],
  [1196, 'Easy Games'],
  [1201, '1v1 Games'],
  [1205, 'Tycoon Games', true],
  [1206, 'Brainrot Games', true],
  [1209, 'Roblox Games', true]
]

export const audienceCatalog: AudienceDefinition[] = audienceEntries.map(([id, name, enabledForTesting]) => ({
  id,
  name,
  enabled_for_testing: enabledForTesting === true
}))
