name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and Test
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: yarn
    - name: yarn
      run: |
        yarn
