name: Lint

on: [push]

jobs:
  build:
    runs-on: hetzner

    steps:
    - uses: actions/checkout@v4
    - name: Build and Test
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Enable Corepack
      run: corepack enable
    - name: yarn
      run: |
        yarn
